language: java

install: "./.travis_install.sh"

script: mvn test -Dtest=fr.inria.astor.test.repair.evaluation.JGenProgTest,fr.inria.astor.test.repair.evaluation.MutRepairTest,fr.inria.astor.test.repair.evaluation.IntroClassTest,fr.inria.astor.test.repair.evaluation.EvoSuiteGenerationTest

jdk:
  - oraclejdk8

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    - martin.monperrus@univ-lille1.fr
    - matias.sebastian.martinez@usi.ch
